name: 'Test action'
on:
  pull_request:
    branches:
      - 'master'
  release:
    branches:
      - 'master'
    types:
      - created
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test args reader'
        id: parse_commit_args
        uses: LamaAni/parse-commit-args-action@master

      - name: 'show args'
        run: bash -c "echo "$THE_ARGS"; echo "$THE_OPTIONS"
        env:
          THE_ARGS: ${{steps.parse_commit_args.outputs.args}}
          THE_OPTIONS: ${{steps.parse_commit_args.outputs}}
