name: 'Test action'
on:
  pull_request:
    types:
      - synchronize
      - opened
      - closed
      - edited
      - reopened
    branches:
      - 'master'
  release:
    branches:
      - 'master'
    types:
      - created
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the code'
        uses: actions/checkout@v2

      - name: 'Test args reader'
        id: parse_commit_args
        run: node parse_commit_args.js
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PRINT_GITHUB_CONTEXT: true

      - name: 'show args'
        run: echo "$THE_ARGS"
        env:
          THE_ARGS: '${{ toJSON(steps.parse_commit_args.outputs) }}'

  # prepare:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Create the run matrix'
  #       id: set-matrix
  #       run: echo "::set-output name=matrix::{num:[0,1,2]}"
  #   outputs:
  #     matrix: '{num:[0,1,2]}'

  # paralell:
  #   needs:
  #     - prepare
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
  #   steps:
  #     - name: 'Checkout the code'
  #       uses: actions/checkout@v2

  #     - name: 'Test args reader'
  #       id: parse_commit_args
  #       uses: LamaAni/parse-commit-args-action@master

  #     - name: 'Echo value'
  #       run: echo "$THEVAL"
  #       env:
  #         THEVAL: ${{matrix.num}}

